-- =============================================================================
-- 01 - RBAC: least-privilege custom roles
--   ROLE_LOADER  : write role for ingestion + dbt; OWNS BRONZE/STAGING/MARTS
--   ROLE_ANALYST : read-only role for Power BI; SELECT on MARTS only
-- =============================================================================

-- --- Create the roles (role management is USERADMIN's job) ---
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS ROLE_LOADER  COMMENT = 'Write role: ingestion + dbt';
CREATE ROLE IF NOT EXISTS ROLE_ANALYST COMMENT = 'Read-only role: Power BI, marts only';

-- --- Wire up the role hierarchy + assign to the user (SECURITYADMIN) ---
USE ROLE SECURITYADMIN;
-- Roll custom roles up to SYSADMIN so admins keep visibility.
GRANT ROLE ROLE_LOADER  TO ROLE SYSADMIN;
GRANT ROLE ROLE_ANALYST TO ROLE SYSADMIN;
-- Give the human user both roles (he switches "hats" per task).
GRANT ROLE ROLE_LOADER  TO USER KCHOJNACKI96;
GRANT ROLE ROLE_ANALYST TO USER KCHOJNACKI96;

-- --- Privileges. Done as ACCOUNTADMIN, the current owner of the objects. ---
USE ROLE ACCOUNTADMIN;

-- Both roles need a warehouse to run queries, and USAGE on the database.
GRANT USAGE ON WAREHOUSE WH_XS_ELT     TO ROLE ROLE_LOADER;
GRANT USAGE ON WAREHOUSE WH_XS_ELT     TO ROLE ROLE_ANALYST;
GRANT USAGE ON DATABASE COMMODITY_RISK TO ROLE ROLE_LOADER;
GRANT USAGE ON DATABASE COMMODITY_RISK TO ROLE ROLE_ANALYST;

-- ===== ROLE_LOADER: owns BRONZE / STAGING / MARTS =====
-- COPY CURRENT GRANTS keeps grants already on the objects intact after the
-- ownership transfer (e.g. the analyst grants added below stay valid).
GRANT OWNERSHIP ON SCHEMA COMMODITY_RISK.BRONZE  TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA COMMODITY_RISK.STAGING TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA COMMODITY_RISK.MARTS   TO ROLE ROLE_LOADER COPY CURRENT GRANTS;

-- Transfer ownership of everything already inside those schemas.
GRANT OWNERSHIP ON ALL TABLES       IN SCHEMA COMMODITY_RISK.BRONZE  TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL STAGES       IN SCHEMA COMMODITY_RISK.BRONZE  TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA COMMODITY_RISK.BRONZE  TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS        IN SCHEMA COMMODITY_RISK.STAGING TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES       IN SCHEMA COMMODITY_RISK.MARTS   TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS        IN SCHEMA COMMODITY_RISK.MARTS   TO ROLE ROLE_LOADER COPY CURRENT GRANTS;

-- The external stage reads ADLS via the storage integration; let LOADER use it.
GRANT USAGE ON INTEGRATION azure_adls_int TO ROLE ROLE_LOADER;

-- ===== ROLE_ANALYST: read-only on MARTS (Gold) only =====
GRANT USAGE  ON SCHEMA COMMODITY_RISK.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL    TABLES IN SCHEMA COMMODITY_RISK.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA COMMODITY_RISK.MARTS TO ROLE ROLE_ANALYST;
-- ...and on anything created there later, so new marts are readable automatically.
GRANT SELECT ON FUTURE TABLES IN SCHEMA COMMODITY_RISK.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA COMMODITY_RISK.MARTS TO ROLE ROLE_ANALYST;

-- --- Inspect the result ---
SHOW GRANTS TO ROLE ROLE_LOADER;
SHOW GRANTS TO ROLE ROLE_ANALYST;
