-- =============================================================================
-- 06 - Zero-copy clone: dev environment from prod, instantly and for ~0 storage
--   COMMODITY_RISK       = prod
--   COMMODITY_RISK_DEV   = zero-copy clone (shares micro-partitions; copy-on-write)
--
-- REFRESH FLOW: re-run this script. CREATE OR REPLACE drops the old clone and
-- makes a fresh one from the CURRENT state of prod (again instant, ~0 storage).
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- The clone itself: instant, no data copied.
CREATE OR REPLACE DATABASE COMMODITY_RISK_DEV CLONE COMMODITY_RISK;

-- Clones do NOT inherit the source object's grants, so re-apply the RBAC from
-- 01_rbac_roles.sql on the clone: ROLE_LOADER owns it (dbt writes here in dev),
-- ROLE_ANALYST reads MARTS only.
GRANT USAGE ON DATABASE COMMODITY_RISK_DEV TO ROLE ROLE_LOADER;
GRANT USAGE ON DATABASE COMMODITY_RISK_DEV TO ROLE ROLE_ANALYST;

GRANT OWNERSHIP ON SCHEMA COMMODITY_RISK_DEV.BRONZE  TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA COMMODITY_RISK_DEV.STAGING TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA COMMODITY_RISK_DEV.MARTS   TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA COMMODITY_RISK_DEV.BRONZE  TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA COMMODITY_RISK_DEV.STAGING TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS  IN SCHEMA COMMODITY_RISK_DEV.STAGING TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA COMMODITY_RISK_DEV.MARTS   TO ROLE ROLE_LOADER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS  IN SCHEMA COMMODITY_RISK_DEV.MARTS   TO ROLE ROLE_LOADER COPY CURRENT GRANTS;

GRANT USAGE  ON SCHEMA COMMODITY_RISK_DEV.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL    TABLES IN SCHEMA COMMODITY_RISK_DEV.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA COMMODITY_RISK_DEV.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA COMMODITY_RISK_DEV.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA COMMODITY_RISK_DEV.MARTS TO ROLE ROLE_ANALYST;

-- Proof: the clone holds the same data as prod (created in milliseconds).
SELECT 'prod' AS env, COUNT(*) AS mart_rows FROM COMMODITY_RISK.MARTS.FCT_FX_RATES
UNION ALL
SELECT 'dev'  AS env, COUNT(*)             FROM COMMODITY_RISK_DEV.MARTS.FCT_FX_RATES;
